<a href="https://colab.research.google.com/github/luanakwon/2021-2_ML/blob/main/KHgyu_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# B811011 권준현 midterm 
!pip install turicreate
import numpy as np
import turicreate as tc

(a)

In [ ]:
# my own set of weights w0 ~ w10
weights = np.array([1,4,1,5,9,2,6,5,3,5,8])

# generated actual input data
# random uniform between 0 and 10
np.random.seed(0)
data_x = np.random.uniform(0,10,size=(1000,10))

print(data_x)
print(data_x.shape)

# Y data for these input data
# small random variation to imply noise
rdm_w = np.matmul(np.ones((1000,1)),np.reshape(weights,(1,11)))
rdm_w += np.random.normal(0,0.5,size=(1000,11))
data_y = np.sum(data_x*rdm_w[:,1:], axis=1) + rdm_w[:,0]

# print(data_y)
print(data_y.shape)

[[5.48813504 7.15189366 6.02763376 ... 8.91773001 9.63662761 3.83441519]
 [7.91725038 5.2889492  5.68044561 ... 8.32619846 7.78156751 8.70012148]
 [9.78618342 7.99158564 4.61479362 ... 9.44668917 5.21848322 4.1466194 ]
 ...
 [4.09316583 8.16221102 0.11549241 ... 3.76742895 6.9770858  8.48420392]
 [4.78316574 8.46360039 5.48319338 ... 7.65341815 5.2550272  9.91043203]
 [6.94983329 1.94606892 1.14036759 ... 7.58429521 0.23787427 8.1357508 ]]
(1000, 10)
(1000,)


In [ ]:
data = tc.SFrame()
for i in range(10):
  data['x'+str(i+1)] = data_x[:,i]
data['y'] = data_y

data

Columns:
	x1	float
	x2	float
	x3	float
	x4	float
	x5	float
	x6	float
	x7	float
	x8	float
	x9	float
	x10	float
	y	float

Rows: 1000

Data:
+--------------------+--------------------+--------------------+
|         x1         |         x2         |         x3         |
+--------------------+--------------------+--------------------+
| 5.4881350392732475 | 7.151893663724195  | 6.027633760716439  |
| 7.917250380826646  | 5.288949197529044  | 5.680445610939323  |
|  9.78618342232764  | 7.9915856421672355 | 4.6147936225293185 |
|  2.64555612104627  | 7.742336894342166  | 4.5615033221654855 |
|  3.59507900573786  | 4.3703195379934145 | 6.976311959272649  |
| 5.701967704178797  | 4.386015134623204  | 9.883738380592263  |
| 1.5896958364551972 | 1.1037514116430513 | 6.563295894652734  |
| 9.764594650133958  | 4.686512016477016  | 9.767610881903371  |
| 3.1798317939397602 |  4.1426299451467   | 0.6414749634878436 |
| 3.1856895245132364 | 6.674103799636817  | 1.3179786240439217 |
+--------------------+--------------------+--------------------+
+--------------------+---------------------+---------------------+
|         x4         |          x5         |          x6         |
+--------------------+---------------------+---------------------+
| 5.448831829968968  |  4.236547993389047  |  6.458941130666561  |
|  9.25596638292661  |  0.7103605819788694 |  0.8712929970154071 |
| 7.805291762864554  |  1.1827442586893322 |  6.399210213275238  |
| 5.684339488686485  | 0.18789800436355142 |  6.176354970758771  |
| 0.6022547162926983 |  6.667667154456677  |  6.706378696181594  |
| 1.0204481074802807 |  2.088767560948347  |  1.6130951788499626 |
| 1.381829513486138  |  1.965823616800535  |  3.687251706609641  |
|  6.04845519745046  |  7.3926357939830165 | 0.39187792254320675 |
| 6.924721193700199  |  5.666014542065751  |  2.653894909394454  |
| 7.163272041185655  |  2.894060929472011  |  1.8319136200711683 |
+--------------------+---------------------+---------------------+
+--------------------+---------------------+--------------------+
|         x7         |          x8         |         x9         |
+--------------------+---------------------+--------------------+
| 4.375872112626925  |  8.917730007820797  | 9.636627605010293  |
| 0.2021839744032572 |   8.32619845547938  | 7.781567509498505  |
| 1.433532874090464  |  9.446689170495839  | 5.218483217500717  |
| 6.120957227224214  |  6.169339968747569  | 9.437480785146242  |
| 2.103825610738409  |  1.289262976548533  | 3.1542835092418384 |
| 6.531083254653984  |  2.532916025397821  | 4.663107728563062  |
| 8.209932298479352  |  0.9710127579306127 | 8.379449074988038  |
| 2.828069625764096  |  1.201965612131689  | 2.9614019752214493 |
| 5.232480534666997  |  0.9394051075844168 | 5.759464955561793  |
| 5.865129348100831  | 0.20107546187493552 | 8.289400292173632  |
+--------------------+---------------------+--------------------+
+----------------------+--------------------+
|         x10          |         y          |
+----------------------+--------------------+
|  3.8344151882577773  | 276.4163333897636  |
|  8.700121482468191   | 298.1956379387116  |
|  4.146619399905235   | 286.53977557192593 |
|  6.818202991034834   | 267.46935054324166 |
|  3.637107709426226   | 161.26634314033967 |
|  2.4442559200160274  | 172.15067117352655 |
|  0.9609840789396307  | 179.68528710252676 |
|  1.1872771895424405  | 199.99739352852322 |
|  9.292961975762141   | 239.93775894144358 |
| 0.046954761925470656 | 184.75531266003765 |
+----------------------+--------------------+
[1000 rows x 11 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [ ]:
train, test = data.random_split(0.8, seed=0)

linear_model = tc.linear_regression.create(train,target='y',validation_set=None)

Linear regression:

--------------------------------------------------------

Number of examples          : 797

Number of features          : 10

Number of unpacked features : 10

Number of coefficients    : 11

Starting Newton Method

--------------------------------------------------------

+-----------+----------+--------------+--------------------+---------------------------------+

| Iteration | Passes   | Elapsed Time | Training Max Error | Training Root-Mean-Square Error |

+-----------+----------+--------------+--------------------+---------------------------------+

| 1         | 2        | 0.002064     | 55.481836          | 12.728472                       |

+-----------+----------+--------------+--------------------+---------------------------------+

In [ ]:
linear_model.coefficients.print_rows(11,4)

--------------------------------------------------------

+-----------+----------+--------------+--------------------+----------------------+---------------------------------+-----------------------------------+

| Iteration | Passes   | Elapsed Time | Training Max Error | Validation Max Error | Training Root-Mean-Square Error | Validation Root-Mean-Square Error |

+-----------+----------+--------------+--------------------+----------------------+---------------------------------+-----------------------------------+

| 1         | 2        | 0.001199     | 29.817534          | 28.768910            | 9.007331                        | 9.602281                          |

+-----------+----------+--------------+--------------------+----------------------+---------------------------------+-----------------------------------+

SUCCESS: Optimal solution found.

+-------------+-------+--------------------+---------------------+
|     name    | index |       value        |        stderr       |
+-------------+-------+--------------------+---------------------+
| (intercept) |  None | 3.010695593425666  |  1.8491557868506556 |
|      x1     |  None | 4.197130038605792  | 0.11512485061287664 |
|      x2     |  None | 0.9255120029243428 |  0.1151287418243721 |
|      x3     |  None | 4.780230903265607  |  0.1182123350782511 |
|      x4     |  None | 8.938598596126969  |  0.1133523095487603 |
|      x5     |  None | 2.012759941247394  | 0.11177562098229146 |
|      x6     |  None | 5.887111998095054  | 0.11756628166928529 |
|      x7     |  None | 4.889780994308064  | 0.11881503522414702 |
|      x8     |  None | 3.0359673602703996 |  0.1131725976753266 |
|      x9     |  None | 4.980904378512788  | 0.10959667641027247 |
|     x10     |  None | 7.870597446701043  | 0.11790577113798466 |
+-------------+-------+--------------------+------------------

(b)

In [ ]:
data_x[:,5] = 2*data_x[:,1]-3*data_x[:,2]
data_x[:,6] = data_x[:,0] + data_x[:,4] + data_x[:,9]
data_y = np.sum(data_x*rdm_w[:,1:], axis=1) + rdm_w[:,0]

data['x6'] = data_x[:,5]
data['x7'] = data_x[:,6]
data['y'] = data_y

data

Columns:
	x1	float
	x2	float
	x3	float
	x4	float
	x5	float
	x6	float
	x7	float
	x8	float
	x9	float
	x10	float
	y	float

Rows: 1000

Data:
+--------------------+--------------------+--------------------+
|         x1         |         x2         |         x3         |
+--------------------+--------------------+--------------------+
| 5.4881350392732475 | 7.151893663724195  | 6.027633760716439  |
| 7.917250380826646  | 5.288949197529044  | 5.680445610939323  |
|  9.78618342232764  | 7.9915856421672355 | 4.6147936225293185 |
|  2.64555612104627  | 7.742336894342166  | 4.5615033221654855 |
|  3.59507900573786  | 4.3703195379934145 | 6.976311959272649  |
| 5.701967704178797  | 4.386015134623204  | 9.883738380592263  |
| 1.5896958364551972 | 1.1037514116430513 | 6.563295894652734  |
| 9.764594650133958  | 4.686512016477016  | 9.767610881903371  |
| 3.1798317939397602 |  4.1426299451467   | 0.6414749634878436 |
| 3.1856895245132364 | 6.674103799636817  | 1.3179786240439217 |
+--------------------+--------------------+--------------------+
+--------------------+---------------------+---------------------+
|         x4         |          x5         |          x6         |
+--------------------+---------------------+---------------------+
| 5.448831829968968  |  4.236547993389047  |  -3.779113954700925 |
|  9.25596638292661  |  0.7103605819788694 |  -6.46343843775988  |
| 7.805291762864554  |  1.1827442586893322 |  2.1387904167465166 |
| 5.684339488686485  | 0.18789800436355142 |  1.8001638221878764 |
| 0.6022547162926983 |  6.667667154456677  | -12.188296801831116 |
| 1.0204481074802807 |  2.088767560948347  |  -20.87918487253038 |
| 1.381829513486138  |  1.965823616800535  | -17.482384860672102 |
|  6.04845519745046  |  7.3926357939830165 |  -19.92980861275608 |
| 6.924721193700199  |  5.666014542065751  |  6.360834999829869  |
| 7.163272041185655  |  2.894060929472011  |  9.394271727141868  |
+--------------------+---------------------+---------------------+
+--------------------+---------------------+--------------------+
|         x7         |          x8         |         x9         |
+--------------------+---------------------+--------------------+
| 13.559098220920072 |  8.917730007820797  | 9.636627605010293  |
| 17.327732445273707 |   8.32619845547938  | 7.781567509498505  |
| 15.115547080922209 |  9.446689170495839  | 5.218483217500717  |
| 9.651657116444655  |  6.169339968747569  | 9.437480785146242  |
| 13.899853869620763 |  1.289262976548533  | 3.1542835092418384 |
| 10.234991185143171 |  2.532916025397821  | 4.663107728563062  |
| 4.516503532195363  |  0.9710127579306127 | 8.379449074988038  |
| 18.34450763365942  |  1.201965612131689  | 2.9614019752214493 |
| 18.138808311767654 |  0.9394051075844168 | 5.759464955561793  |
| 6.126705215910718  | 0.20107546187493552 | 8.289400292173632  |
+--------------------+---------------------+--------------------+
+----------------------+--------------------+
|         x10          |         y          |
+----------------------+--------------------+
|  3.8344151882577773  | 255.6546448067883  |
|  8.700121482468191   | 346.3733296742553  |
|  4.146619399905235   | 330.81639176274507 |
|  6.818202991034834   | 255.22219668439442 |
|  3.637107709426226   | 106.75877325301099 |
|  2.4442559200160274  | 53.66574175097252  |
|  0.9609840789396307  |  52.6284296234555  |
|  1.1872771895424405  | 171.38549975355465 |
|  9.292961975762141   | 324.35972399493863 |
| 0.046954761925470656 | 234.1628016212917  |
+----------------------+--------------------+
[1000 rows x 11 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [ ]:
train, test = data.random_split(0.8,seed=0)

mse_rdg_model = tc.linear_regression.create(train,target='y',l2_penalty=1, validation_set=None)

Linear regression:

--------------------------------------------------------

Number of examples          : 797

Number of features          : 10

Number of unpacked features : 10

Number of coefficients    : 11

Starting Newton Method

--------------------------------------------------------

+-----------+----------+--------------+--------------------+---------------------------------+

| Iteration | Passes   | Elapsed Time | Training Max Error | Training Root-Mean-Square Error |

+-----------+----------+--------------+--------------------+---------------------------------+

| 1         | 2        | 0.001741     | 55.455002          | 12.730944                       |

+-----------+----------+--------------+--------------------+---------------------------------+

SUCCESS: Optimal solution found.

In [ ]:
mse_rdg_model.coefficients.print_rows(11,4)

+-------------+-------+---------------------+---------------------+
|     name    | index |        value        |        stderr       |
+-------------+-------+---------------------+---------------------+
| (intercept) |  None |  2.210096459407406  |  2.2648713600568264 |
|      x1     |  None |  6.295612507123252  |         nan         |
|      x2     |  None |  5.354013341409169  |  1909114.4287179173 |
|      x3     |  None | -1.8976387644502701 |  2853995.0742543754 |
|      x4     |  None |   8.95272784799756  | 0.15545078313797292 |
|      x5     |  None |   4.31472382100411  |         nan         |
|      x6     |  None |  3.720063599267736  |  959623.1936049967  |
|      x7     |  None |  2.756067891318464  |         nan         |
|      x8     |  None |  2.9589773046162007 | 0.15557675937970616 |
|      x9     |  None |  5.104398273266794  | 0.15065405289124703 |
|     x10     |  None |  10.08110958228602  |         nan         |
+-------------+-------+---------------------+---

x1, x2, x3, x5, x6, x7, x10 은 다른 feature 와 interdependent 하기 때문에, 학습한 parameter를 보면 정확히 학습하지 못했음을 알 수 있다.  
반대로 x4, x8, x9 는 각각 9, 3, 5 와 유사한 값으로 정확히 학습했음을 알 수 있다.

[2]  
gradient decent method 를 사용하고 있다.  

coefficient 에 해당되는 price_per_room의 식을 살펴보면, `lr*x*(y-y')` 인데, 이는 MSE Loss 의 gradient 인 `2*(y-y')*(-x)`에 `lr/2` 를 곱한 후 뺀(decent) 식과 동일함을 알 수 있다. 따라서 featured의 coefficient 를 업데이트 할 때 Gradient Decent Method 를 사용했음을 알 수 있다.  

마찬가지로, bias 에 해당하는 base_price의 식을 살펴보면, `lr*(y-y')` 인데, 역시 동일한 gradient 식에 x=1 을 대입한 `2*(y-y')*(-1)` 에 `lr/2` 를 곱한 후 뺀 형태임을 알 수 있다.

[3]  
(a)  
ML2 와 ML1 의 varience 는 거의 같다고 볼 수 있다. 하지만 ML2가 ML1보다 데이터들과 거리가 있다. 다시말해서, ML2 의 bias가 ML1 보다 크기 때문에, ML1의 모델이 데이터를 더 잘 표현한다고 볼 수 있다.

(b)  
해당 모델이 logistic classifier 일 경우 ML1의 도식은 ML2와 같이 모두 정확히 분류했지만, probability 또는 likelihood 가 ML2에 비해 떨어진다고 해석된다. Logistic classifier 의 objective는 정확히 분류하는것과 함께, 각 데이터 포인트의 likelihood 를 높이는 것이기 때문에, ML2의 모델이 더 잘 학습하였다고 볼 수 있다.

[4]  
각 셀에 한글 주석으로 썼습니다.

In [ ]:
# Load the data
# 예시에서 주어진 데이터셋이 제공되지 않아 코랩에서 제공되는 csv 파일중 일부를 읽어 사용함
data = tc.SFrame.read_csv('/content/sample_data/mnist_train_small.csv',verbose=False,header=False, nrows=6000)

# Make a train-test split
# 성능 테스트를 위해 4:1 로 랜덤 분리
train_data, test_data = data.random_split(0.8)

# Create a model
# 타겟이 'label'에서 'X1' 으로 명칭만 변경
model = tc.logistic_classifier.create(train_data, target='X1')

# Save predictions to an SFrame (class and corresponding class-probabilities)
predictions = model.classify(test_data)

# Top 5 predictions with probabilities, rank, and margin
# 각각 probability, margin, rank 기준으로 가장 높은 예측들을 클래스당 5개씩 선출
top = model.predict_topk(test_data, output_type='probability', k = 5)
top = model.predict_topk(test_data, output_type='rank', k = 5)
top = model.predict_topk(test_data, output_type='margin', k = 5)

# Evaluate the model and save the results into a dictionary
results = model.evaluate(test_data)

PROGRESS: Creating a validation set from 5 percent of training data. This may take a while.
          You can set ``validation_set=None`` to disable validation tracking.



Logistic regression:

--------------------------------------------------------

Number of examples          : 4609

Number of classes           : 10

Number of feature columns   : 784

Number of unpacked features : 784

Number of coefficients      : 7065

Starting L-BFGS

--------------------------------------------------------

+-----------+----------+-----------+--------------+-------------------+---------------------+

| Iteration | Passes   | Step size | Elapsed Time | Training Accuracy | Validation Accuracy |

+-----------+----------+-----------+--------------+-------------------+---------------------+

| 0         | 2        | 1.000000  | 0.228869     | 0.598394          | 0.567901            |

| 1         | 4        | 1.000000  | 0.473406     | 0.698199          | 0.629630            |

| 2         | 6        | 1.000000  | 0.710131     | 0.770449          | 0.707819            |

| 3         | 7        | 1.000000  | 0.864831     | 0.824040          | 0.786008            |

| 4         | 8        | 1.000000  | 1.022095     | 0.848340          | 0.827160            |

| 9         | 14       | 1.000000  | 1.872326     | 0.910176          | 0.864198            |

+-----------+----------+-----------+--------------+-------------------+---------------------+

In [ ]:
# 각 id 별로 probability 가 가장 높은 3개씩 출력
top = model.predict_topk(test_data, output_type='probability', k = 3)
print(top)

+----+-------+------------------------+
| id | class |      probability       |
+----+-------+------------------------+
| 0  |   0   |  0.022992141979427116  |
| 0  |   5   |   0.9679952463309917   |
| 0  |   8   |  0.005357014770763095  |
| 1  |   9   |  0.005261713822534874  |
| 1  |   7   |   0.9947368877787186   |
| 1  |   0   | 1.0677536830261403e-06 |
| 2  |   8   |   0.0863351196203465   |
| 2  |   6   |   0.8527001945754997   |
| 2  |   1   |  0.016217452027680667  |
| 3  |   3   |  0.12664238310684092   |
+----+-------+------------------------+
[3450 rows x 3 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.
